import java.util.*;
import static net.mindview.util.Print.*;
public class Chapter2 {
	static void streq(String s1, String s2){
		print("s1 == s2:" + (s1 == s2));
		print("s1 equals s2:" + s1.equals(s2));
		print("s1 != s2:" + (s1 != s2));
		print("s1 not equals s2:" + !(s1.equals(s2)));
		
	}
	public static void main(String[] args) {
		print("Hello");
		System.out.println("Hi");
		Tank t1 = new Tank();
		Tank t2 = new Tank();
		t1.level = 1.1f;
		t2.level = 2.2f;
		print("t1.level:" + t1.level + " t2.level:" + t2.level);
		t1 = t2;
		print("t1.level:" + t1.level + " t2.level:" + t2.level);
		t1.level = 3.3f;
		print("t1.level:" + t1.level + " t2.level:" + t2.level);
		PassObject.init();
		int s = 100;
		int t = 20;
		double v = s / t;
		print ("v = " + v);
		Dog spot = new Dog();
		Dog scruffy = new Dog();
		spot.name = "Spot";
		spot.says = "Hav hav";
		scruffy.name = "Scruffy";
		scruffy.says = "Rrrrr";
		print(spot.name + spot.says);
		print(scruffy.name + scruffy.says);
		Dog clone = new Dog();
		clone = spot;
		print(clone == spot);
		print(clone.equals(spot));
		Random rand = new Random();
		boolean i = rand.nextBoolean();
		print(i);
		long d;
		d = 0xffe;
		print (Long.toBinaryString(d));
		d = 0175;
		print (Long.toBinaryString(d));
		double expDouble = -4.9e-324;
		float expFloat =  -1.4e-45f;
		print (expDouble);
		print (expFloat);
		expDouble = 1.7e+308;
		expFloat = 3.4e+38f;
		print (expDouble);
		print (expFloat);
		int a = 0xaaa;
		int b = 0xbbb;
		print (Integer.toBinaryString(a));
		print (Integer.toBinaryString(b));
		int c = a&b;
		print (Integer.toBinaryString(c));
		c = a|b;
		print (Integer.toBinaryString(c));
		c = a^b;
		print (Integer.toBinaryString(c));
		a = 0xa;
		print (Integer.toBinaryString(a));
		a >>= 1;
		print (Integer.toBinaryString(a));
		a >>= 1;
		print (Integer.toBinaryString(a));
		a >>= 1;
		print (Integer.toBinaryString(a));
		a >>= 1;
		print (Integer.toBinaryString(a));
		a = 0xf;
		print (Integer.toBinaryString(a));
		a <<= 1;
		print (Integer.toBinaryString(a));
		a >>>=1;
		print (Integer.toBinaryString(a));
		a >>>=1;
		print (Integer.toBinaryString(a));
		a >>>=1;
		print (Integer.toBinaryString(a));
		a >>>=1;
		print (Integer.toBinaryString(a));
		a >>>=1;
		print (Integer.toBinaryString(a));
		char g = 'b';
		a = g;
		print (Integer.toBinaryString(a));
		g = 'c';
		a = g;
		print (Integer.toBinaryString(a));
		streq ("soda","soda");
	}
}
